### ISSUE TITLE
No change input function in both Companion v2 and v3

### ISSUE THREAD

**Issue by acidfrost** [bitfocus/companion-module-novastar-controller#47]
In the help, it says we can change the input of the listed novastar model, but the action is not listed at all. We tried both Companion 2 and 3:

![image](https://github.com/bitfocus/companion-module-novastar-controller/assets/68562713/8b9098ff-a5ab-4899-9f96-6fb0b4d70ab8)

**Comment by istnv** [comment]
Which model? The features listed are what the module provides. Not every model supports every command.

**Comment by acidfrost** [comment]
We have Novastar MCTRL4K, but I've toggled to every other models in companion and none of them have the option appear.

**Comment by istnv** [comment]
v2 had an issue that was fixed in v3. Have you tried the latest (v3.1.2)? 
I use the MCTRL4K daily.

**Comment by acidfrost** [comment]
We are still on Companion 2.4.2 at this time as because some modules of other devices we have are still not updated. We are connected via network to the novastar and the connection is active.

I do use 3.1.2 at home and I don't see the **change input** action when selecting it. See screenshot in op of what I see. Does it need to be connected to the actual novastar to appear in 3.1.2? Thanks

**Comment by istnv** [comment]
You should be able to change the model on the configuration tab where the IP is set. Remember to press 'Save'.
After that the options/actions for that model should be available:
![image](https://github.com/bitfocus/companion-module-novastar-controller/assets/51003420/e9f0797d-bdc8-4c16-82ae-81b94b066c15)

This is from a MCTRL4K that is actually turned off this week.

**Comment by acidfrost** [comment]
Negative here. This is on 3.1.2 See:

![image](https://github.com/bitfocus/companion-module-novastar-controller/assets/68562713/39a22f58-9bf9-417b-ad7b-f1cb61a77dc3)

![image](https://github.com/bitfocus/companion-module-novastar-controller/assets/68562713/f2d76fbe-6f6f-422f-a402-f4989a7db9c3)

**Comment by acidfrost** [comment]
OH wait! I figured it out. Once you've setup your connection. You have to fully quit companion, shut it off. Then restart companion and the proper options are there:

![image](https://github.com/bitfocus/companion-module-novastar-controller/assets/68562713/f03c263f-bc3c-4138-9b51-2d00e044d23b)

That is an odd bug.

**Comment by istnv** [comment]
It has been there for a while. I thought it was fixed. In v3 you can toggle the enable switch on the far right:
![image](https://github.com/bitfocus/companion-module-novastar-controller/assets/51003420/3fa17c89-64ce-46b9-ada7-f94b754955c9)

It is supposed to update that list when you hit save.

**Comment by istnv** [comment]
Fixed in betas.
